# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: stalomeow/metrics@projects-v2 # lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: SuperslowJelly
          template: classic
          debug: yes
          retries: 3
          retries_delay: 300
          base: activity, repositories, metadata
          extras_css: |
            h2, h3 {
              color: #F1C40F;
            }
          config_display: large
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_days: 183
          plugin_habits_facts: no
          plugin_habits_from: 200
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_music: no
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: top         # Set plugin mode
          plugin_music_limit: 8          # Limit to 4 entries, maximum is 50 for "top" mode with spotify
          plugin_music_top_type: artists  # Set type for "top" mode; either tracks or artists
          plugin_music_time_range: long # Set time range for "top" mode; either short (4 weeks), medium (6 months) or long (several years)
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_traffic: yes
          repositories_forks: yes
          repositories_skipped: Superslowjelly/superslowJelly, SuperslowJelly/Dev-Resources
